package com.ms_products.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for product response data.
 * <p>
 * This class is used to send product information to the client.
 * It includes the unique database identifier and all relevant
 * business fields.
 * </p>
 * @version 1.0
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProductResponseDTO {

    /**
     * Unique identifier generated by the database.
     */
    private Long id;

    /**
     * The commercial name of the product.
     */
    private String name;

    /**
     * Unique business code (KPI) for the product.
     */
    private String code;

    /**
     * Current unit price of the product.
     */
    private Double price;

    /**
     * Available quantity in inventory.
     */
    private Integer stock;

    /**
     * Category name to which the product belongs.
     */
    private String category;
}